version: "3"

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=mbta
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  api:
    build: ./api/
    image: mbta-api
    command: sh -c "dockerize -wait tcp://db:5432 && ./manage.py migrate && gunicorn mbta.wsgi -b :8000"
    environment:
      - DJANGO_SETTINGS_MODULE=mbta.settings.prod
      - DB_HOSTNAME=db
      - DB_PASSWORD=root
      - SECRET_KEY
    depends_on:
      - db

  webserver:
    build: ./webapp/
    image: mbta-webserver
    depends_on:
      - api
    ports:
      - "80:80"
