version: "3"

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=mbta
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  api:
    build: ./api/
    image: mbta-api
    command: sh -c "dockerize -wait tcp://db:5432 && ./manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_PASSWORD=root
    depends_on:
      - db
  # webapp:
  #   image: node:10-alpine
  #   working_dir: /app/webapp
  #   command: sh -c "npm install && npm start"
  #   environment:
  #     - NODE_ENV=development
  #     - API_HOST=http://api:8000
  #   ports:
  #     - "3000:3000"
