# Generated by Django 2.1.7 on 2019-03-25 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('gtfs_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('line', models.CharField(choices=[('blue', 'Blue Line'), ('green', 'Green Line'), ('orange', 'Orange Line'), ('red', 'Red Line')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StationInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.PositiveSmallIntegerField()),
                ('entries', models.PositiveSmallIntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Station')),
            ],
        ),
    ]
